image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - step:
        name: Checkout repository
        caches:
          - dotnetcore
        script:
          - git checkout $BITBUCKET_BRANCH
          - dotnet restore ColaboratorC.sln
          - dotnet build ColaboratorC.sln --no-restore --configuration Release

    - step:
        name: Run Domain Tests
        caches:
          - dotnetcore
        script:
          - dotnet test ColaboratorC.sln --filter FullyQualifiedName~Domain.Tests --configuration Release
        artifacts:
          - test-results/**

    - step:
        name: Run Integration Tests
        caches:
          - dotnetcore
        services:
          - docker
        script:
          - dotnet restore ColaboratorC.sln
          - dotnet test ColaboratorC.sln --filter FullyQualifiedName~WebApi.IntegrationTests --configuration Release
        artifacts:
          - test-results/**

definitions:
  caches:
    dotnetcore: ~/.nuget/packages
  services:
    docker:
      memory: 2048
