name: .NET CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Start RabbitMQ container
        run: |
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --hostname rabbit rabbitmq:3.13-management
          docker ps -a

      - name: Ensure RabbitMQ is ready
        run: |
          for i in {1..10}; do
            if docker exec rabbitmq rabbitmqctl status; then
              exit 0
            fi
            sleep 3
          done
          exit 1

      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ColaboratorC.sln

      - name: Build
        run: dotnet build ColaboratorC.sln --no-restore --configuration Release

      - name: Stop RabbitMQ container
        if: always()
        run: docker stop rabbitmq

      - name: Remove RabbitMQ container
        if: always()
        run: docker rm rabbitmq

  tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Start RabbitMQ container
        run: |
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 --hostname rabbit rabbitmq:3.13-management
          docker ps -a

      - name: Ensure RabbitMQ is ready
        run: |
          for i in {1..10}; do
            if docker exec rabbitmq rabbitmqctl status; then
              exit 0
            fi
            sleep 3
          done
          exit 1

      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ColaboratorC.sln

      - name: Run Unit Tests
        run: dotnet test ColaboratorC.sln --filter FullyQualifiedName~Domain.Tests --configuration Release

      - name: Run Integration Tests
        run: dotnet test ColaboratorC.sln --filter FullyQualifiedName~WebApi.IntegrationTests --configuration Release

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      - name: Stop RabbitMQ container
        if: always()
        run: docker stop rabbitmq

      - name: Remove RabbitMQ container
        if: always()
        run: docker rm rabbitmq
